name: test

on:
  pull_request:

jobs:
  moon-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: 'lint'
        run: |
          wget https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          ./kubeval moon.yaml
          ./kubeval moon-local.yaml
          ./kubeval moon-monitor.yaml --ignore-missing-schemas
          wget -O tools.tar.gz https://artifacts-openshift-release-3-11.svc.ci.openshift.org/zips/openshift-origin-client-tools-v3.11.0-8f721f2-450-linux-64bit.tar.gz
          tar xf tools.tar.gz openshift-origin-client-tools-v3.11.0-8f721f2-450-linux-64bit/oc
          ./oc process -f moon-openshift.yaml --local=true 2>&1 > /dev/null
